kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-pv-001
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/elastic/data01"
